### PR TITLE
Add Fmt.{failwith, invalid_arg}

### LINKED ISSUE #24: Add Fmt.{invalid_arg,failwith}
Raising the corresponding exceptions.

```ocaml
val Fmt.failwith : ('a, Format.formatter, unit, unit) format4 -> 'a
val Fmt.invalid_arg : ('a, Format.formatter, unit, unit) format4 -> 'a
```

### PR DESCRIPTION
**Pull request by hcarty**
Closes #24

### CODE REVIEW

**Comment by hcarty** [comment]
I wasn't sure how terse to keep the doc comments - please let me know if you'd prefer just the `[failwith] is [kstrf failwith]` text as the comment string.

**Comment by dbuenzli** [comment]
Thanks your patch is in as eb07861d2a5292e7a16ff97, I slightly tweaked the doc string in a2d065bfc555264edf688c6.

**Comment by hcarty** [comment]
Thank you! The tweaked doc strings are definitely an improvement.

**Comment by hcarty** [comment]
And apologies for not including a changes entry - I completely missed that.

**Comment by dbuenzli** [comment]
> And apologies for not including a changes entry - I completely missed that.

Bah np the commit is sufficently clear so `topkg status` will make that a breeze.

**Pull request closed without merging**
