### PR TITLE
Add more data combinators.

### PR DESCRIPTION
**Pull request by Drup**
The type of the set one is a bit scary, but it's actually easy to use.

### CODE REVIEW

**Comment by hcarty** [comment]
`set` looks quite nice.

**Comment by Drup** [comment]
It's possible to generalize the set combinator by defining the fold module signature 
```ocaml
  module type Fold = sig
    type t
    type elt
    val fold : (elt -> 'a -> 'a) -> t -> 'a -> 'a
  end
```

and taking that instead. It would work out of the box.

Or just take a fold function ...

**Comment by hcarty** [comment]
What about a `map` equivalent (`Map.S`)?  In that case `fold` takes an extra parameter.  It could be wrapped to fold over `(key, value)` tuples but that would be less easy/convenient.

**Comment by dbuenzli** [comment]
Closing this in favour of 959eedc.

Formatters for sets and map can use: 

* ```Fmt.iter Set.iter pp_elt```
* ```Fmt.iter_bindings Map.iter pp_binding```

Sets and maps can be dumped with: 

* ```Fmt.(Dump.iter Set.iter (always "set") pp_elt)```
* ```Fmt.(Dump.iter_bindings Map.iter_bindings (always "map") pp_k pp_v)```

**Pull request closed without merging**
